-- ============================================
-- AI FEATURES MIGRATION
-- Adds fields for AI-powered features
-- ============================================

-- ============================================
-- PROFILES TABLE UPDATES
-- ============================================

-- AI Onboarding tracking
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ai_onboarding_completed BOOLEAN DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS life_stage TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS priorities TEXT[] DEFAULT '{}';

-- ============================================
-- GOALS TABLE UPDATES
-- ============================================

-- Track AI-generated goals
ALTER TABLE goals ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false;

-- Goal refinement suggestions
ALTER TABLE goals ADD COLUMN IF NOT EXISTS is_vague BOOLEAN DEFAULT false;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS ai_refinement_suggestion TEXT;

-- Subtasks - already exists as JSONB, but ensure it exists
-- subtasks format: [{ "text": "...", "completed": false, "estimated_time": "1 hour" }]

-- ============================================
-- AI CHAT HISTORY TABLE (optional - for context)
-- ============================================
CREATE TABLE IF NOT EXISTS ai_chat_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE ai_chat_history ENABLE ROW LEVEL SECURITY;

-- Policies for ai_chat_history
CREATE POLICY "Users can view own chat history" ON ai_chat_history
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own chat messages" ON ai_chat_history
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own chat history" ON ai_chat_history
  FOR DELETE USING (auth.uid() = user_id);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_chat_history_user ON ai_chat_history(user_id, created_at DESC);

-- Keep only last 50 messages per user (cleanup function)
CREATE OR REPLACE FUNCTION cleanup_old_chat_messages()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM ai_chat_history
  WHERE user_id = NEW.user_id
  AND id NOT IN (
    SELECT id FROM ai_chat_history
    WHERE user_id = NEW.user_id
    ORDER BY created_at DESC
    LIMIT 50
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-cleanup
DROP TRIGGER IF EXISTS cleanup_chat_history_trigger ON ai_chat_history;
CREATE TRIGGER cleanup_chat_history_trigger
  AFTER INSERT ON ai_chat_history
  FOR EACH ROW
  EXECUTE FUNCTION cleanup_old_chat_messages();

-- ============================================
-- WEEKLY DIGEST TRACKING
-- ============================================

-- Track when last digest was sent
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_digest_sent_at TIMESTAMPTZ;

-- ============================================
-- COMMENTS
-- ============================================
COMMENT ON COLUMN profiles.ai_onboarding_completed IS 'Whether user completed AI onboarding flow';
COMMENT ON COLUMN profiles.life_stage IS 'User life stage for personalized AI suggestions';
COMMENT ON COLUMN profiles.priorities IS 'User priority areas for AI goal generation';
COMMENT ON COLUMN goals.is_ai_generated IS 'Whether this goal was generated by AI';
COMMENT ON COLUMN goals.is_vague IS 'AI determined this goal needs refinement';
COMMENT ON COLUMN goals.ai_refinement_suggestion IS 'AI suggested SMART version of the goal';
